import test from 'node:test';
import assert from 'node:assert/strict';

import { ScenarioQuestionSchema } from '../src/model/scenarioSchema.js';
import { ArchitectureModelSchema } from '../src/model/schema.js';

/**
 * Representative formal model used to verify the structural contract.
 * The values are explicit inputs, not numbers generated by the LLM.
 */
const validModel = {
  modelVersion: '1.0',
  architectureName: 'Checkout Platform',
  services: [
    {
      id: 'checkout-api',
      name: 'Checkout API',
      replicas: 4,
      capacityRpsPerReplica: 80,
      baselineLatencyMs: 120
    },
    {
      id: 'pricing-service',
      name: 'Pricing Service',
      replicas: 2,
      capacityRpsPerReplica: 100,
      baselineLatencyMs: 150
    }
  ],
  dataStores: [
    {
      id: 'orders-db',
      name: 'PostgreSQL',
      type: 'relational',
      replicas: 1,
      capacityRpsPerReplica: null,
      baselineLatencyMs: 20
    }
  ],
  dependencies: [
    {
      from: 'checkout-api',
      to: 'pricing-service',
      callType: 'sync',
      required: true,
      timeoutMs: 2000,
      retryPolicy: {
        maxRetries: 3,
        backoff: 'exponential'
      },
      circuitBreaker: null
    },
    {
      from: 'checkout-api',
      to: 'orders-db',
      callType: 'sync',
      required: true,
      timeoutMs: 1000,
      retryPolicy: null,
      circuitBreaker: null
    }
  ],
  incomingLoadRps: 100,
  declaredTargets: {
    availabilityPercent: 99.9,
    maximumLatencyMs: null,
    minimumThroughputRps: null
  },
  assumptions: [
    'All retry attempts reach the downstream dependency.'
  ],
  missingInformation: [
    'Availability measurement window was not provided.'
  ],
  sourceEvidence: [
    'Checkout API runs with four replicas at 80 RPS each.'
  ]
};

test('accepts a structurally valid architecture model', () => {
  const result = ArchitectureModelSchema.safeParse(validModel);

  assert.equal(result.success, true);
});

test('rejects a service with zero replicas in the base model', () => {
  const invalidModel = structuredClone(validModel);
  invalidModel.services[0].replicas = 0;

  const result = ArchitectureModelSchema.safeParse(invalidModel);

  assert.equal(result.success, false);
});

test('accepts a circuit breaker on an asynchronous dependency', () => {
  const model = structuredClone(validModel);

  model.services.push({
    id: 'notification-queue',
    name: 'Notification Queue',
    replicas: 2,
    capacityRpsPerReplica: 500,
    baselineLatencyMs: 10
  });

  model.dependencies[0] = {
    from: 'checkout-api',
    to: 'pricing-service',
    callType: 'async',
    required: false,
    timeoutMs: null,
    retryPolicy: {
      maxRetries: 0,
      backoff: 'none'
    },
    circuitBreaker: {
      failureThreshold: 5,
      openDurationMs: 30000,
      halfOpenMaxCalls: 1,
      messageBufferComponentId: 'notification-queue',
      openBehavior: 'retain_in_queue'
    }
  };

  const result = ArchitectureModelSchema.safeParse(model);

  assert.equal(result.success, true);
});

test('rejects a non-positive circuit-breaker failure threshold', () => {
  const model = structuredClone(validModel);

  model.dependencies[0].circuitBreaker = {
    failureThreshold: 0,
    openDurationMs: 30000,
    halfOpenMaxCalls: 1,
    messageBufferComponentId: 'orders-db',
    openBehavior: 'retain_in_queue'
  };

  const result = ArchitectureModelSchema.safeParse(model);

  assert.equal(result.success, false);
});

test('accepts the formal circuit-breaker scenario structure', () => {
  const scenario = {
    type: 'circuit_breaker_state_change',
    componentId: null,
    newLatencyMs: null,
    latencyMultiplier: null,
    loadMultiplier: null,
    circuitBreakerFrom: 'notification-consumer',
    circuitBreakerTo: 'email-service',
    circuitBreakerState: 'open',
    unsupportedReason: null,
    missingInformation: [],
    assumptions: []
  };

  const result = ScenarioQuestionSchema.safeParse(scenario);

  assert.equal(result.success, true);
});

test('rejects an unknown circuit-breaker state', () => {
  const scenario = {
    type: 'circuit_breaker_state_change',
    componentId: null,
    newLatencyMs: null,
    latencyMultiplier: null,
    loadMultiplier: null,
    circuitBreakerFrom: 'notification-consumer',
    circuitBreakerTo: 'email-service',
    circuitBreakerState: 'recovering',
    unsupportedReason: null,
    missingInformation: [],
    assumptions: []
  };

  const result = ScenarioQuestionSchema.safeParse(scenario);

  assert.equal(result.success, false);
});
