import test from 'node:test';
import assert from 'node:assert/strict';

import { ArchitectureModelSchema } from '../src/model/schema.js';

/**
 * Representative formal model used to verify the structural contract.
 * The values are explicit inputs, not numbers generated by the LLM.
 */
const validModel = {
  modelVersion: '1.0',
  architectureName: 'Checkout Platform',
  services: [
    {
      id: 'checkout-api',
      name: 'Checkout API',
      replicas: 4,
      capacityRpsPerReplica: 80,
      baselineLatencyMs: 120
    },
    {
      id: 'pricing-service',
      name: 'Pricing Service',
      replicas: 2,
      capacityRpsPerReplica: 100,
      baselineLatencyMs: 150
    }
  ],
  dataStores: [
    {
      id: 'orders-db',
      name: 'PostgreSQL',
      type: 'relational',
      replicas: 1,
      capacityRpsPerReplica: null,
      baselineLatencyMs: 20
    }
  ],
  dependencies: [
    {
      from: 'checkout-api',
      to: 'pricing-service',
      callType: 'sync',
      required: true,
      timeoutMs: 2000,
      retryPolicy: {
        maxRetries: 3,
        backoff: 'exponential'
      }
    },
    {
      from: 'checkout-api',
      to: 'orders-db',
      callType: 'sync',
      required: true,
      timeoutMs: 1000,
      retryPolicy: null
    }
  ],
  incomingLoadRps: 100,
  declaredTargets: {
    availabilityPercent: 99.9,
    maximumLatencyMs: null,
    minimumThroughputRps: null
  },
  assumptions: [
    'All retry attempts reach the downstream dependency.'
  ],
  missingInformation: [
    'Availability measurement window was not provided.'
  ],
  sourceEvidence: [
    'Checkout API runs with four replicas at 80 RPS each.'
  ]
};

test('accepts a structurally valid architecture model', () => {
  const result = ArchitectureModelSchema.safeParse(validModel);

  assert.equal(result.success, true);
});

test('rejects a service with zero replicas in the base model', () => {
  const invalidModel = structuredClone(validModel);
  invalidModel.services[0].replicas = 0;

  const result = ArchitectureModelSchema.safeParse(invalidModel);

  assert.equal(result.success, false);
});